"""CI-helper regressions using disposable repositories/archives, never Release/.

Consistent ZIPs below are test fixtures only. The real public ZIP is deliberately
not regenerated by this suite, including when its documentation is stale.
"""
import ast
import hashlib
import io
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import tempfile
import unittest
import warnings
import zipfile
from unittest import mock

ROOT = pathlib.Path(__file__).resolve().parents[1]


def environment(**changes):
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE='1')
    for name in ('GITHUB_REF_TYPE', 'GITHUB_REF_NAME', 'PYTHONOPTIMIZE'):
        env.pop(name, None)
    env.update(changes)
    return env


class ReleaseVerifier(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='broadcomvtd-verifier-fixture-')
        self.addCleanup(self.temporary.cleanup)
        self.root = pathlib.Path(self.temporary.name)/'repo'
        self.root.mkdir()
        for name in ('POC', 'Config', 'Docs', 'Release', 'Licenses', 'tools'):
            shutil.copytree(ROOT/name, self.root/name, ignore=shutil.ignore_patterns('__pycache__', '.DS_Store'))
        for name in ('README.md', 'RELEASE_NOTES_v0.2.17.md', 'RELEASE_NOTES_v0.2.25.md', 'LICENSE', 'THIRD_PARTY_NOTICES.md', 'Makefile'):
            if (ROOT/name).exists():
                shutil.copy2(ROOT/name, self.root/name)
        self.identity = json.loads((self.root/'Release/identity.json').read_text())
        self.package = {
            'INSTALL.md': 'Release/INSTALL.md',
            'RELEASE_NOTES_v0.2.17.md': 'RELEASE_NOTES_v0.2.17.md',
            'LICENSE': 'LICENSE',
            'THIRD_PARTY_NOTICES.md': 'THIRD_PARTY_NOTICES.md',
            'Licenses/Lilu-BSD-3-Clause.txt': 'Licenses/Lilu-BSD-3-Clause.txt',
            'Licenses/MacKernelSDK-APSL-2.0.txt': 'Licenses/MacKernelSDK-APSL-2.0.txt',
            'identity.json': 'Release/identity.json',
        }
        self.archive()

    def archive(self, stale=None, duplicate=False, omit=None, extra=False):
        name = self.identity['project']+'-'+self.identity['tag']+'.zip'
        path = self.root/'Release'/name
        entries = {member: (self.root/source).read_bytes() for member, source in self.package.items()}
        entries.update({'BroadcomVTD.kext/'+member: (self.root/'Release/BroadcomVTD.kext'/member).read_bytes()
                        for member in self.identity['bundle_files']})
        if stale:
            entries[stale] = b'Stale test-fixture documentation\n'
        if omit:
            del entries[omit]
        if extra:
            entries['unverified-extra.txt'] = b'not part of the release layout\n'
        with zipfile.ZipFile(path, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
            for member, data in sorted(entries.items()):
                archive.writestr(member, data)
            if duplicate:
                with warnings.catch_warnings():
                    warnings.simplefilter('ignore', UserWarning)
                    archive.writestr('LICENSE', entries['LICENSE'])
        (self.root/'Release/SHA256SUMS').write_text(hashlib.sha256(path.read_bytes()).hexdigest()+'  '+name+'\n')

    def verify(self, args=(), **env):
        return subprocess.run([sys.executable, '-B', str(self.root/'tools/verify_release.py'), *args],
                              cwd=self.root, env=environment(**env), text=True,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

    def success(self, result):
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn('PASS exact frozen source', result.stdout)

    def failure(self, result, reason):
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn(reason, result.stdout)

    def test_normal_local(self):
        self.success(self.verify())

    def test_normal_branch(self):
        self.success(self.verify(GITHUB_REF_TYPE='branch', GITHUB_REF_NAME='main'))

    def test_matching_tag(self):
        self.success(self.verify(GITHUB_REF_TYPE='tag', GITHUB_REF_NAME=self.identity['tag']))

    def test_mismatching_tag(self):
        self.failure(self.verify(GITHUB_REF_TYPE='tag', GITHUB_REF_NAME='v9.9.9'), 'Tag/version mismatch')

    def test_require_tag_without_ref(self):
        self.failure(self.verify(['--require-tag']), '--require-tag requires')

    def test_require_tag_branch(self):
        self.failure(self.verify(['--require-tag'], GITHUB_REF_TYPE='branch', GITHUB_REF_NAME='main'), '--require-tag requires')

    def test_require_tag_exact(self):
        self.success(self.verify(['--require-tag'], GITHUB_REF_TYPE='tag', GITHUB_REF_NAME=self.identity['tag']))

    def test_require_tag_missing_name(self):
        self.failure(self.verify(['--require-tag'], GITHUB_REF_TYPE='tag'), 'Tag/version mismatch')

    def test_require_tag_wrong_name(self):
        self.failure(self.verify(['--require-tag'], GITHUB_REF_TYPE='tag', GITHUB_REF_NAME='v9.9.9'), 'Tag/version mismatch')

    def test_duplicate_zip_member(self):
        self.archive(duplicate=True)
        self.failure(self.verify(), 'Duplicate ZIP member names')

    def test_stale_release_notes(self):
        self.archive(stale='RELEASE_NOTES_v0.2.17.md')
        self.failure(self.verify(), 'Stale packaged repository files: RELEASE_NOTES_v0.2.17.md')

    def test_stale_install(self):
        self.archive(stale='INSTALL.md')
        self.failure(self.verify(), 'Stale packaged repository files: INSTALL.md')

    def test_stale_project_license(self):
        self.archive(stale='LICENSE')
        self.failure(self.verify(), 'Stale packaged repository files: LICENSE')

    def test_stale_other_packaged_files(self):
        for name in ('THIRD_PARTY_NOTICES.md', 'Licenses/Lilu-BSD-3-Clause.txt',
                     'Licenses/MacKernelSDK-APSL-2.0.txt', 'identity.json'):
            with self.subTest(member=name):
                self.archive(stale=name)
                self.failure(self.verify(), 'Stale packaged repository files: '+name)

    def test_missing_packaged_file(self):
        self.archive(omit='INSTALL.md')
        self.failure(self.verify(), 'Unexpected or missing release ZIP files')

    def test_unverified_extra_file(self):
        self.archive(extra=True)
        self.failure(self.verify(), 'Unexpected or missing release ZIP files')

    def test_frozen_source_still_checked(self):
        path = self.root/'POC/MapperCore.cpp'
        path.write_bytes(path.read_bytes()+b'\n// test-fixture divergence\n')
        self.failure(self.verify(), 'Frozen source divergence')


class OptimizationGuard(unittest.TestCase):
    def test_assert_heavy_helpers_reject_optimization_before_work(self):
        with tempfile.TemporaryDirectory(prefix='broadcomvtd-opt-fixture-') as temporary:
            root = pathlib.Path(temporary)
            for name in ('verify_release.py', 'repeat_public_build.py', 'validate_public_build.py'):
                script = root/'tools'/name
                script.parent.mkdir(exist_ok=True)
                shutil.copy2(ROOT/'tools'/name, script)
                for flags, env in [(['-O'], {}), (['-OO'], {}), ([], {'PYTHONOPTIMIZE': '1'})]:
                    with self.subTest(script=name, flags=flags, env=env):
                        result = subprocess.run([sys.executable, '-B', *flags, str(script)], cwd=root,
                                                env=environment(**env), text=True,
                                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                        self.assertNotEqual(result.returncode, 0, result.stdout)
                        self.assertIn('Python optimization disables validation assertions', result.stdout)
                        self.assertNotIn('Traceback', result.stdout)
                        self.assertFalse((root/'build').exists())


class DependencyCache(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='broadcomvtd-cache-fixture-')
        self.addCleanup(self.temporary.cleanup)
        self.root = pathlib.Path(self.temporary.name)
        for name in ('tools', 'Config', 'cache', 'guard'):
            (self.root/name).mkdir()
        shutil.copy2(ROOT/'tools/fetch_dependencies.py', self.root/'tools/fetch_dependencies.py')
        # A process-local network sentinel proves cache failures never attempt a
        # real network request. The explicit network-mode test supplies fake data.
        (self.root/'guard/sitecustomize.py').write_text(
            "import os, urllib.request\n"
            "def guarded_urlopen(*args, **kwargs):\n"
            "    source = os.environ.get('BRCMVTD_FAKE_NETWORK_ARCHIVE')\n"
            "    if not source: raise RuntimeError('NETWORK_FALLBACK_FORBIDDEN')\n"
            "    print('TEST_NETWORK_BRANCH_USED')\n"
            "    return open(source, 'rb')\n"
            "urllib.request.urlopen = guarded_urlopen\n")
        self.cache_archive()

    def cache_archive(self, member='fixture/input.txt', kind=None, link=None, extra=False):
        stream = io.BytesIO()
        with tarfile.open(fileobj=stream, mode='w:gz') as archive:
            info = tarfile.TarInfo(member)
            if kind is not None:
                info.type = kind
                info.linkname = link or ''
                archive.addfile(info)
            else:
                info.size = 7
                archive.addfile(info, io.BytesIO(b'fixture'))
            if extra:
                info = tarfile.TarInfo('second/input.txt')
                info.size = 7
                archive.addfile(info, io.BytesIO(b'fixture'))
        data = stream.getvalue()
        (self.root/'cache/TestDependency.tar.gz').write_bytes(data)
        lock = {'TestDependency': {'commit': 'test-fixture', 'url': 'https://example.invalid/archive',
                                   'sha256': hashlib.sha256(data).hexdigest()}}
        (self.root/'Config/dependencies.lock.json').write_text(json.dumps(lock))

    def fetch(self, cached=True, fake_network=False):
        env = environment(PYTHONPATH=str(self.root/'guard'))
        env.pop('BRCMVTD_FAKE_NETWORK_ARCHIVE', None)
        if fake_network:
            env['BRCMVTD_FAKE_NETWORK_ARCHIVE'] = str(self.root/'cache/TestDependency.tar.gz')
        args = ['--archive-cache', str(self.root/'cache')] if cached else []
        return subprocess.run([sys.executable, '-B', str(self.root/'tools/fetch_dependencies.py'), *args],
                              cwd=self.root, env=env, text=True,
                              stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

    def failure(self, reason):
        result = self.fetch()
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn(reason, result.stdout)
        self.assertNotIn('NETWORK_FALLBACK_FORBIDDEN', result.stdout)
        return result

    def test_correct_cache(self):
        result = self.fetch()
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertEqual((self.root/'.deps/TestDependency/input.txt').read_bytes(), b'fixture')
        self.assertNotIn('TEST_NETWORK_BRANCH_USED', result.stdout)

    def test_missing_cache_has_no_network_fallback(self):
        (self.root/'cache/TestDependency.tar.gz').unlink()
        self.failure('missing cached archive')

    def test_wrong_hash(self):
        (self.root/'cache/TestDependency.tar.gz').write_bytes(b'wrong hash')
        self.failure('archive SHA-256 mismatch')

    def test_existing_destination(self):
        self.assertEqual(self.fetch().returncode, 0)
        self.failure('exists; use a fresh dependency directory')

    def test_no_cache_preserves_network_branch(self):
        result = self.fetch(cached=False, fake_network=True)
        self.assertEqual(result.returncode, 0, result.stdout)
        self.assertIn('TEST_NETWORK_BRANCH_USED', result.stdout)

    def test_escaping_archive_path(self):
        self.cache_archive(member='../escape')
        self.failure('Unsafe archive member')
        self.assertFalse((self.root/'.deps/escape').exists())

    def test_escaping_archive_link(self):
        for kind in (tarfile.SYMTYPE, tarfile.LNKTYPE):
            with self.subTest(kind=kind):
                self.cache_archive(member='fixture/link', kind=kind, link='../../outside')
                self.failure('Unsafe archive link')

    def test_devices_and_fifos(self):
        for kind in (tarfile.CHRTYPE, tarfile.FIFOTYPE):
            with self.subTest(kind=kind):
                self.cache_archive(member='fixture/device', kind=kind)
                self.failure('Unsafe archive member')

    def test_multiple_archive_roots(self):
        self.cache_archive(extra=True)
        self.failure('Unexpected archive root')


class SanitizerEnvironment(unittest.TestCase):
    def setUp(self):
        # Execute only the actual environment function, not the suite/builds.
        tree = ast.parse((ROOT/'tools/test_public.py').read_text())
        function = next(node for node in tree.body
                        if isinstance(node, ast.FunctionDef) and node.name == 'command_environment')
        settings = {target.id: ast.literal_eval(node.value)
                    for node in tree.body if isinstance(node, ast.Assign)
                    for target in node.targets if isinstance(target, ast.Name)
                    and target.id == 'SANITIZER_ENV'}
        self.executable = '/fixture/poc-private-sanitized'
        namespace = dict(settings, os=os, sanitized_executables={self.executable})
        exec(compile(ast.Module(body=[function], type_ignores=[]),
                     str(ROOT/'tools/test_public.py'), 'exec'), namespace)
        self.command_environment = namespace['command_environment']

    def test_sanitized_execution_enforces_options_and_preserves_environment(self):
        inherited = {'PATH': '/fixture/bin', 'BRCMVTD_TEST_SENTINEL': 'kept',
                     'PYTHONDONTWRITEBYTECODE': '0', 'ASAN_OPTIONS': 'halt_on_error=0',
                     'UBSAN_OPTIONS': 'halt_on_error=0'}
        with mock.patch.dict(os.environ, inherited, clear=True):
            env = self.command_environment([self.executable, 'golden'])
            self.assertEqual(env, dict(inherited, PYTHONDONTWRITEBYTECODE='1',
                                      ASAN_OPTIONS='halt_on_error=1', UBSAN_OPTIONS='halt_on_error=1'))
            self.assertEqual(dict(os.environ), inherited)

    def test_other_commands_do_not_inject_sanitizer_options(self):
        inherited = {'PATH': '/fixture/bin', 'BRCMVTD_TEST_SENTINEL': 'kept'}
        commands = [['/fixture/poc-private-optimized', 'golden'],
                    ['clang++', '-fsanitize=address,undefined', '-o', self.executable],
                    [sys.executable, '-B', 'tools/generate_poc_private_test.py'],
                    [sys.executable, '-B', '-m', 'unittest', 'discover']]
        with mock.patch.dict(os.environ, inherited, clear=True):
            for command in commands:
                with self.subTest(command=command):
                    self.assertEqual(self.command_environment(command),
                                     dict(inherited, PYTHONDONTWRITEBYTECODE='1'))

    def test_ordinary_commands_preserve_inherited_sanitizer_options(self):
        inherited = {'ASAN_OPTIONS': 'detect_leaks=0', 'UBSAN_OPTIONS': 'print_stacktrace=1'}
        with mock.patch.dict(os.environ, inherited, clear=True):
            self.assertEqual(self.command_environment(['/fixture/poc-tx_cleanup']),
                             dict(inherited, PYTHONDONTWRITEBYTECODE='1'))


class SanitizerFailure(unittest.TestCase):
    def test_actual_suite_settings_stop_intentional_undefined_behavior(self):
        tree = ast.parse((ROOT/'tools/test_public.py').read_text())
        settings = {target.id: ast.literal_eval(node.value)
                    for node in tree.body if isinstance(node, ast.Assign)
                    for target in node.targets if isinstance(target, ast.Name)
                    and target.id in ('SANITIZER_FLAGS', 'SANITIZER_ENV')}
        flags = settings['SANITIZER_FLAGS']
        options = settings['SANITIZER_ENV']
        self.assertIn('-fsanitize=address,undefined', flags)
        self.assertIn('-fno-sanitize-recover=undefined', flags)
        self.assertEqual(options, {'ASAN_OPTIONS': 'halt_on_error=1', 'UBSAN_OPTIONS': 'halt_on_error=1'})
        if shutil.which('xcrun') is None:
            self.skipTest('xcrun is not available on this platform')
        cc = subprocess.check_output(['xcrun', '--find', 'clang++'], text=True).strip()
        sdk = subprocess.check_output(['xcrun', '--sdk', 'macosx', '--show-sdk-path'], text=True).strip()
        with tempfile.TemporaryDirectory(prefix='broadcomvtd-ubsan-probe-') as temporary:
            root = pathlib.Path(temporary)
            source = root/'overflow.cpp'
            source.write_text('#include <limits.h>\nint main() { volatile int n = INT_MAX; '
                              'int result = n + 1; (void)result; return 0; }\n')
            command = [cc, '-std=c++14', '-isysroot', sdk, '-pthread', *flags, str(source), '-o', str(root/'probe')]
            build = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
            self.assertEqual(build.returncode, 0, build.stdout)
            result = subprocess.run([str(root/'probe')], text=True, stdout=subprocess.PIPE,
                                    stderr=subprocess.STDOUT, env=dict(os.environ, PYTHONDONTWRITEBYTECODE='1', **options))
            self.assertNotEqual(result.returncode, 0, result.stdout)
            self.assertIn('runtime error: signed integer overflow', result.stdout)
            output = ROOT/'build/poc-0.2.25'
            output.mkdir(parents=True, exist_ok=True)
            (output/'sanitizer-fail-closed-proof.json').write_text(json.dumps({
                'result': 'PASS', 'probe': 'intentional signed integer overflow',
                'flags_from_actual_test_public': flags, 'runtime_environment': options,
                'probe_exit_code': result.returncode, 'probe_output': result.stdout,
                'physical_validation': False}, indent=2)+'\n')


if __name__ == '__main__':
    unittest.main()
